### ISSUE TITLE
Can no longer add or change note title as of recent update.

### ISSUE THREAD

**Issue by dreamsengraved** [shadowkras/NeatNoter#6]
Title. Thank you!

**Comment by shadowkras** [comment]
Also, from a feedback on Dalamud's discord (thanks Vhein#4706):
> Feedback for NeatNoter
> Hello, since the last update it seems i cannot edit the name of my notes ? It doesn't let me write or even delete the text placed there.

**Comment by shadowkras** [comment]
Issue was a ImGuiInputTextFlags.ReadOnly flag added to the title input on the normal window, it was supposed to be added only on the overlay window to prevent editing it by accident.
